# Generated by Django 3.1.3 on 2021-05-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210516_2058'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tweet_id',
            new_name='tweet',
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('tweet', 'created_at')},
        ),
    ]
